#!/bin/bash

keypriv=$1
keypub=$2
image=$3

echo "sign image"

cosign sign --key ${keypriv} localhost:1338/demo/${image}

echo "check this can be verified"

cosign verify --key ${keypub} localhost:1338/demo/${image}


