#!/bin/bash

[ -x $(which registry) ] || { echo "No registry binary available"; exit 1; }

echo "Start Registry server"

if [ $(uname -s) == "Darwin" ]; then
	setsid nohup registry &
else
	setsid nohup registry | systemd-cat --identifier=oci-registry &
fi

