#!/bin/bash

key=$1
image=$2

if [ ${key} = "-h" ]; then
	echo "$0 [cosign key] [image id]"
	echo "e.g:"
	echo "$0 ${HOME}/cosign/cosign.key rekor-cli-e3df3bc7cfcbe584a2639931193267e9"
	exit
fi

echo "sign image"

COSIGN_EXPERIMENTAL=1 cosign sign --key ${key} --rekor-url=http://localhost:3000 localhost:1338/demo/${image}

echo "check this can be verified"

COSIGN_EXPERIMENTAL=1 cosign verify --key ${key} --rekor-url=http://localhost:3000 localhost:1338/demo/${image}


